const fonts = [
  ["Arial", "Helvetica", "sans-serif"],
  ["Times New Roman", "Georgia", "serif"],
  ["Courier New", "Courier", "monospace"],
  ["Roboto", "Open Sans", "sans-serif"],
  ["Garamond", "Palatino", "serif"],
  ["Comic Sans MS", "cursive", "sans-serif"],
  ["Verdana", "Tahoma", "sans-serif"],
  ["Baskerville", "Libre Baskerville", "serif"],
  ["Consolas", "Monaco", "monospace"],
  ["Brush Script MT", "cursive", "sans-serif"],
  ["Impact", "Charcoal", "sans-serif"],
  ["Lato", "Raleway", "sans-serif"],
  ["Papyrus", "Fantasy", "cursive"],
  ["Calibri", "Candara", "sans-serif"],
  ["Bookman", "URW Bookman", "serif"],
  ["Poppins", "Montserrat", "sans-serif"],
  ["Playfair Display", "Lora", "serif"],
  ["Fira Code", "Source Code Pro", "monospace"],
  ["Dancing Script", "Pacifico", "cursive"],
  ["Bebas Neue", "Oswald", "sans-serif"],
  ["Quicksand", "Nunito", "sans-serif"],
  ["Fredoka One", "Luckiest Guy", "cursive"],
  ["Merriweather", "PT Serif", "serif"],
  ["Cinzel", "Old Standard TT", "serif"],
  ["Indie Flower", "Amatic SC", "cursive"],
  ["Exo 2", "Josefin Sans", "sans-serif"],
  ["Cormorant", "Alegreya", "serif"],
  ["IBM Plex Mono", "JetBrains Mono", "monospace"],
  ["Kaushan Script", "Great Vibes", "cursive"],
  ["Russo One", "Archivo Black", "sans-serif"],
  ["Work Sans", "Rubik", "sans-serif"],
  ["Lobster", "Chewy", "cursive"],
  ["Source Sans Pro", "Noto Sans", "sans-serif"],
  ["Prata", "Crimson Text", "serif"],
  ["Permanent Marker", "Caveat", "cursive"],
  ["Anton", "Barlow", "sans-serif"],
  ["Libre Caslon Text", "DM Serif Display", "serif"],
  ["Space Mono", "Overpass Mono", "monospace"],
  ["Sacramento", "Parisienne", "cursive"],
  ["Black Ops One", "Press Start 2P", "sans-serif"],
  ];

  export default fonts;