const languageCodes = [
    "en-US", // English (United States)
    "en-GB", // English (United Kingdom)
    "fr-FR", // French (France)
    "fr-CA", // French (Canada)
    "es-ES", // Spanish (Spain)
    "es-MX", // Spanish (Mexico)
    "de-DE", // German (Germany)
    "it-IT", // Italian (Italy)
    "pt-PT", // Portuguese (Portugal)
    "pt-BR", // Portuguese (Brazil)
    "ru-RU", // Russian (Russia)
    "zh-CN", // Chinese (Simplified)
    "zh-TW", // Chinese (Traditional)
    "ja-JP", // Japanese (Japan)
    "ko-KR", // Korean (South Korea)
    "ar-SA", // Arabic (Saudi Arabia)
    "nl-NL", // Dutch (Netherlands)
    "sv-SE", // Swedish (Sweden)
    "no-NO", // Norwegian (Norway)
    "da-DK", // Danish (Denmark)
    "fi-FI", // Finnish (Finland)
    "pl-PL", // Polish (Poland)
    "tr-TR", // Turkish (Turkey)
    "cs-CZ", // Czech (Czech Republic)
    "hu-HU", // Hungarian (Hungary)
    "ro-RO", // Romanian (Romania)
    "el-GR", // Greek (Greece)
    "he-IL", // Hebrew (Israel)
    "th-TH", // Thai (Thailand)
    "vi-VN", // Vietnamese (Vietnam)
    "id-ID", // Indonesian (Indonesia)
    "ms-MY", // Malay (Malaysia)
    "hi-IN", // Hindi (India)
    "bn-BD", // Bengali (Bangladesh)
    "ta-IN", // Tamil (India)
    "ur-PK", // Urdu (Pakistan)
    "fa-IR"  // Persian (Iran)
  ];

export default languageCodes;