const timezones = [
    "America/New_York", "America/Los_Angeles", "America/Chicago", "America/Denver", 
    "America/Phoenix", "America/Detroit", "America/Indianapolis",
    "America/Indianapolis",
    "America/Toronto", "America/Vancouver",
    "America/Edmonton", "America/Halifax", "America/Winnipeg", "America/Regina",
    "America/St_Johns", "America/Guatemala", "America/Belize",
    "America/Tegucigalpa", "America/Santo_Domingo", "America/Havana", "America/Panama",
    "Europe/London", "Europe/Paris", "Europe/Berlin", "Europe/Madrid", 
    "Europe/Rome", "Europe/Amsterdam", "Europe/Brussels", "Europe/Vienna",
    "Europe/Stockholm", "Europe/Oslo", "Europe/Copenhagen", "Europe/Zagreb",
    "Europe/Helsinki", "Europe/Sofia", "Europe/Prague", "Europe/Belgrade",
    "Europe/Bucharest", "Europe/Amsterdam", "Europe/Zurich", "Europe/Minsk",
    "Asia/Tokyo", "Asia/Dubai", "Asia/Singapore", "Asia/Hong_Kong", 
    "Asia/Shanghai", "Asia/Seoul", "Asia/Kuala_Lumpur", "Asia/Manila",
    "Asia/Bangkok", "Asia/Jakarta", "Asia/Kolkata", "Asia/Calcutta",
    "Asia/Tehran", "Asia/Yerevan", "Asia/Tashkent", "Asia/Almaty",
    "Asia/Baku", "Asia/Dhaka", "Asia/Colombo", "Asia/Phnom_Penh",
    "Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane", "Australia/Perth",
    "Australia/Adelaide", "Australia/Hobart", "Australia/Darwin", "Australia/Canberra",
    "Pacific/Auckland", "Pacific/Fiji", "Pacific/Port_Moresby", "Pacific/Chatham",
    "Africa/Johannesburg", "Africa/Cairo", "Africa/Nairobi", "Africa/Accra",
    "Africa/Lagos", "Africa/Algiers", "Africa/Khartoum", "Africa/Harare",
    "Africa/Maputo", "Africa/Libreville", "Africa/Luanda", "Africa/Brazzaville",
    "America/Caracas", "America/La_Paz", "America/Santiago", "America/Asuncion",
    "America/Montevideo", "Pacific/Apia", "Pacific/Tongatapu", "Pacific/Noumea",
    "Pacific/Guadalcanal", "Atlantic/Azores", "Atlantic/Cape_Verde", "Atlantic/Reykjavik",
    "Etc/GMT+12", "Etc/GMT+11", "Etc/GMT+10", "Etc/GMT+9",
    "Etc/GMT+8", "Etc/GMT+7", "Etc/GMT+6", "Etc/GMT+5",
    "Etc/GMT+4", "Etc/GMT+3", "Etc/GMT+2", "Etc/GMT+1",
    "Etc/GMT", "Etc/GMT-1", "Etc/GMT-2", "Etc/GMT-3",
    "Etc/GMT-4", "Etc/GMT-5", "Etc/GMT-6", "Etc/GMT-7",
    "Etc/GMT-8", "Etc/GMT-9", "Etc/GMT-10", "Etc/GMT-11",
];

export default timezones;